<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <link rel="shortcut icon" href="img/favicon_1.ico">

        <title>Velonic - Responsive Admin Dashboard Template</title>

        <!-- Bootstrap core CSS -->
        <link href="/public/css/bootstrap.min.css" rel="stylesheet">
        <link href="/public/css/bootstrap-reset.css" rel="stylesheet">

        <!--Animation css-->
        <link href="/public/css/animate.css" rel="stylesheet">

        <!--Icon-fonts css-->
        <link href="/public/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="/public/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
        <link href="/public/assets/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

        <!-- Custom styles for this template -->
        <link href="/public/css/style.css" rel="stylesheet">
        <link href="/public/css/helper.css" rel="stylesheet">
    </head>


    <body>

        <div class="wrapper-page shadow-none">
            <div class="ex-page-content text-center">
                <h1><?php echo $this->code;?></h1>
                <h2 class="font-light"><?php echo $this->error;?></h2><br>
                <p><?php echo ($this->message) ? '<pre>'.$this->message.'</pre>' : ''; ?></p>
                <p><?php echo ($this->trace) ? '<pre>'.$this->trace.'</pre>' : ''; ?>
                </p>
                <a class="btn btn-success m-t-20" href="/"><i class="fa fa-angle-left"></i> Back to Dashboard</a>
            </div>
        </div>

        <!-- js placed at the end of the document so the pages load faster -->
        <script src="/public/js/jquery.js"></script>
        <script src="/public/js/bootstrap.min.js"></script>
        <script src="/public/js/pace.min.js"></script>
        <script src="/public/js/wow.min.js"></script>
        <script src="/public/js/jquery.nicescroll.js" type="text/javascript"></script>
        <!--common script for all pages-->
        <script src="/public/js/jquery.app.js"></script>
    </body>
</html>
