<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">


        <link rel="shortcut icon" href="img/favicon_1.ico">

        <title>Niagara - Domob Access application system.</title>
        <!-- Bootstrap core CSS -->
        <link href="/public/css/bootstrap.min.css" rel="stylesheet">
        <link href="/public/css/bootstrap-reset.css" rel="stylesheet">

        <!--Animation css-->
        <link href="/public/css/animate.css" rel="stylesheet">

        <!--Icon-fonts css-->
        <link href="/public/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="/public/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
        <link href="/public/assets/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

        <!-- Custom styles for this template -->
        <link href="/public/css/style.css" rel="stylesheet">
        <link href="/public/css/helper.css" rel="stylesheet">
        <link href="/public/assets/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
        <link href="/public/assets/datatables/buttons.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public//public//public/assets/datatables/fixedHeader.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public//public/assets/datatables/responsive.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public/assets/datatables/scroller.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public/assets/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />

        <!-- Plugins css -->
        <link href="assets/owl-carousel/owl.carousel.css" rel="stylesheet" />

    </head>
        <script src="/public/js/jquery.js"></script>
        <script src="/public/js/bootstrap.min.js"></script>
    <body>


        <div class="wrapper-page">
            <div class="panel panel-color panel-inverse">
                <div class="panel-heading"> 
                   <h3 class="text-center m-t-10"> Sign In to <strong>Niagara</strong> </h3>
                </div> 

                <div class="panel-body">
                    <form class="form-horizontal m-t-10 p-20 p-b-0" >
                                            
                        <div class="form-group ">
                            <div class="col-xs-12">
                                <input class="form-control" type="text" placeholder="Username" name="username">
                            </div>
                        </div>
                        <div class="form-group ">
                            
                            <div class="col-xs-12">
                                <input class="form-control" type="password" placeholder="Password" name="password">
                            </div>
                        </div>

                        <div class="form-group ">
                            <div class="col-xs-12">
                                <label class="cr-styled">
                                    <input type="checkbox" checked name="autologin">
                                    <i class="fa"></i> 
                                    7天免密码登录
                                </label>
                            </div>
                        </div>
                        <div class="form-group text-right">
                            <div class="col-xs-12">
                                <btn class="btn btn-success w-md" type="">Log In</btn>
                            </div>
                        </div>
                        <div class="form-group m-t-30">
                            <div class="col-sm-7">
                                <a href="/notic/forgotpasswd"><i class="fa fa-lock m-r-5"></i> Forgot your password?</a>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>

        <script src="/public/js/jquery.js"></script>
        <script src="/public/js/bootstrap.min.js"></script>
        <script src="/public/js/pace.min.js"></script>
        <script src="/public/js/wow.min.js"></script>
        <script src="/public/js/jquery.nicescroll.js" type="text/javascript"></script>
        <script src="/public/js/jquery.app.js"></script>
        <script src="/public/js/login/login.js"></script>
    </body>
</html>
