<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">


        <link rel="shortcut icon" href="img/favicon_1.ico">

        <title>Niagara - Domob Access application system.</title>
        <!-- Bootstrap core CSS -->
        <link href="/public/css/bootstrap.min.css" rel="stylesheet">
        <link href="/public/css/bootstrap-reset.css" rel="stylesheet">

        <!--Animation css-->
        <link href="/public/css/animate.css" rel="stylesheet">

        <!--Icon-fonts css-->
        <link href="/public/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="/public/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
        <link href="/public/assets/material-design-iconic-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

        <!-- Custom styles for this template -->
        <link href="/public/css/style.css" rel="stylesheet">
        <link href="/public/css/helper.css" rel="stylesheet">
        <link href="/public/assets/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
        <link href="/public/assets/datatables/buttons.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public//public/assets/datatables/fixedHeader.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public/assets/datatables/responsive.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public/assets/datatables/scroller.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/public/assets/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />

        <!-- Plugins css -->
        <link rel="stylesheet" type="text/css" href="/public/assets/jquery-multi-select/multi-select.css" />
        <link rel="stylesheet" type="text/css" href="/public/assets/select2/select2.css" />
        <link href="/public/assets/modal-effect/css/component.css" rel="stylesheet">


    </head>
        <script src="/public/js/jquery.js"></script>
        <script src="/public/js/bootstrap.min.js"></script>
    <body>

        <!-- Aside Start-->
        <aside class="left-panel">

            <!-- brand -->
            <div class="logo">
                <a href="/index/index" class="logo-expanded">
                    <i class="ion-social-buffer"></i>
                    <span class="nav-label">Niagara</span>
                </a>
            </div>
            <!-- / brand -->
        
            <!-- Navbar Start -->
            <nav class="navigation">
                <ul class="list-unstyled">
                    <li class=""><a href="/index/index"><i class="zmdi zmdi-view-dashboard"></i> <span class="nav-label">欢迎页</span></a></li>
                    <li class="has-submenu <?php G::RenderActive('flow','list')?>" >
                        <a href="/flow/list"><i class="fa fa-edit"></i> <span class="nav-label">新建申请</span></a>
      
                    </li>
                    <li class="has-submenu <?php G::RenderActive('apply')?>" ><a href="/apply/list"><i class="fa fa-file-text-o
"></i> <span class="nav-label">我的申请</span><span class="badge bg-warning"><?=$this->counter['counter_apply']?></span></a>
                    </li>
                    <li class="has-submenu <?php G::RenderActive('approval')?>" ><a href="/approval/list"><i class="fa fa-clipboard"></i> <span class="nav-label">我的审批</span><span class="badge bg-warning"><?=$this->counter['counter_audit']?></span></a>
                    </li>
                    <li class="has-submenu <?php G::RenderActive('group')?>" ><a href="/group/list"><i class="ion-android-contacts"></i> <span class="nav-label">用户组管理</span></a>
                    </li>
                    </li>
                    <li class="has-submenu <?php G::RenderActive('flow','create')?>"><a href="#"><i class="zmdi zmdi-collection-item"></i> <span class="nav-label">申请流程管理</span><span class="menu-arrow"></span></a>
                        <ul class="list-unstyled">
                            <li><a href="/flow/create">创建申请流程</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
                
        </aside>
        <!-- Aside Ends-->


        <!--Main Content Start -->
        <section class="content">
            
            <!-- Header -->
            <header class="top-head container-fluid">
                <button type="button" class="navbar-toggle pull-left">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <!-- Search  Useless Killed.
                <form role="search" class="navbar-left app-search pull-left hidden-xs">
                  <input type="text" placeholder="Search..." class="form-control">
                  <a href=""><i class="fa fa-search"></i></a>
                </form>
                -->
                <!-- Left navbar -->
                <nav class=" navbar-default" role="navigation">
                    <!-- Right navbar -->
                    <ul class="nav navbar-nav navbar-right top-menu top-right-menu">  
                       
                        <!-- user login dropdown start-->
                        <li class="dropdown text-center">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <img alt="" src="/public/img/avatar-2.jpg" class="img-circle profile-img thumb-sm">
                                <span class="username"> </span> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu pro-menu fadeInUp animated" tabindex="5003" style="overflow: hidden; outline: none;">
                                <li><a href="#"><i class="fa fa-briefcase"></i><?php echo $this->user['realname'];?></a></li>
                                <li><a href="/user/logout"><i class="fa fa-sign-out"></i>退出登录</a></li>
                            </ul>
                        </li>
                        <!-- user login dropdown end -->       
                    </ul>
                    <!-- End right navbar -->
                </nav>
                
            </header>
            <!-- Header Ends -->



            <!-- Page Content Start -->
            <!-- ================== -->
            
            <div class="wraper container-fluid">
                <?php if(isset($this->layout['meta_title'])){?>
                <div class="page-title"> 
                    <h3 class="title"><?php echo $this->layout['meta_title']; ?></h3> 
                </div>
                <?php }?>
                 <?php echo $this->content; ?>
            </div>
            
            <!-- Page Content Ends -->
            <!-- ================== -->

            <!-- Footer Start -->
            <footer class="footer">
                2016 © Niagara. Power By Domob - 不二 Team.
            </footer>
            <!-- Footer Ends -->
        </section>
        <!-- Main Content Ends -->

        <script src="/public/js/pace.min.js"></script>
        <script src="/public/js/modernizr.min.js"></script>
        <script src="/public/js/wow.min.js"></script>
        <script src="/public/js/jquery.nicescroll.js" type="text/javascript"></script>
        <script src="/public/js/jquery.app.js"></script>
        <!-- Datatables-->
        <script src="/public/assets/datatables/jquery.dataTables.min.js"></script>
        <script src="/public/assets/datatables/dataTables.bootstrap.js"></script>
        <script src="/public/assets/datatables/dataTables.buttons.min.js"></script>
        <script src="/public/assets/datatables/buttons.bootstrap.min.js"></script>
        <script src="/public/assets/datatables/jszip.min.js"></script>
        <script src="/public/assets/datatables/pdfmake.min.js"></script>
        <script src="/public/assets/datatables/vfs_fonts.js"></script>
        <script src="/public/assets/datatables/buttons.html5.min.js"></script>
        <script src="/public/assets/datatables/buttons.print.min.js"></script>
        <script src="/public/assets/datatables/dataTables.fixedHeader.min.js"></script>
        <script src="/public/assets/datatables/dataTables.keyTable.min.js"></script>
        <script src="/public/assets/datatables/dataTables.responsive.min.js"></script>
        <script src="/public/assets/datatables/responsive.bootstrap.min.js"></script>
        <script src="/public/assets/datatables/dataTables.scroller.min.js"></script>

        <?php 
            //custom srcipt render here.
            Register::render();
        ?>
    </body>
</html>
