<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">增加新的用户组</h3></div>
			<div class="panel-body">
				<form class="form-horizontal p-20" role="form">
					<div class="form-group">
						<label class="col-md-2 control-label">组名称</label>
						<div class="col-md-10">
							<input type="text" class="form-control" value=""></div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">组内成员<br>(一行一条邮箱)</label>
						<div class="col-md-10">
							<textarea class="form-control" rows="10"></textarea>
						</div>
					</div>
					<button type="submit" class="btn btn-purple">提交</button>
					<button type="" class="btn btn-warning">放弃</button>
				</form>
			</div><!-- panel-body -->
		</div><!-- panel -->
	</div><!-- col -->
</div>
