<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">增加新的用户组</h3></div>
			<div class="panel-body">
				<form class="form-horizontal p-20" role="form">
					<div class="form-group">
						<div class="input-group m-t-10">
						  <input type="email" id="group_name"  class="form-control" placeholder="请输入组名" mame="name">
						  <span class="input-group-btn">
						    <button type="button" class="btn btn-effect-ripple btn-primary">提交</button></span>
						</div>
					</div>
					
				</form>
			</div><!-- panel-body -->
		</div><!-- panel -->
	</div><!-- col -->
<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					组列表
				</h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<table class="table">
							<thead>
								<tr>
									<th>
										#
									</th>
									<th>
										组名称
									</th>
									<th>
										成员数
									</th>
									<th>
										操作
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								foreach ($this->grouplist as $group):
								?>
								<tr >
									<td>
										<?php echo $group['group_info']['id'];?>
									</td>
									<td>
										<?php echo $group['group_info']['name'];?>
									</td>
									<td>
										<?php echo count($group['group_members']);?>
									</td>
									<td>
										<a href="/group/show?id=<?php echo $group['group_info']['id'];?>"><button class="btn btn-icon btn-primary m-b-5"> <i class="fa fa-star"></i> </button></a> 
									</td>
								</tr>
								<?php
								endforeach;
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>

	
</div>

<?php
    Register::set('js/group/group.js');
?>