<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">
					组列表
				</h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<table class="table">
							<thead>
								<tr>
									<th>
										#
									</th>
									<th>
										组ID
									</th>
									<th>
										组名称
									</th>
									<th>
										组内成员数
									</th>
									<th>
										操作
									</th>
								</tr>
							</thead>
							<tbody>
								<tr >
									<td>
										1
									</td>
									<td>
										管理员组
									</td>
									<td>
										OPS
									</td>
									<td>
										3
									</td>
									<td>
										删除
									</td>
								</tr>
								
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	
</div>