<div class="row">
        <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">增加用户</h3></div>
            <div class="panel-body">
                <form class="form-horizontal p-20" role="form">
                    <div class="form-group">
                        <div class="input-group ">
                            <select class="select2" multiple   data-placeholder="" name="user">
                                <?php 
                                    foreach ($this->userlist as $user) {
                                        echo '<option value="'.$user['username'].'">'.$user['username'].'</option>';
                                    }
                                ?>
                            </select>

                          <span class="input-group-btn">
                            <button type="button" class="btn btn-effect-ripple btn-primary adduser">提交</button></span>
                        </div>
                    </div>
                    
                </form>
            </div><!-- panel-body -->
        </div><!-- panel -->
    </div><!-- col -->
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?echo $this->group['group_info']['name']?></h3>
                        <input type="hidden" id="groupid" value="<?php echo $this->group['group_info']['id'];?>">
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <table id="datatable" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>邮箱</th>
                                            <th>姓名</th>
                                            <th>所属组</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                  <?php
                                    if(is_array($this->group['group_members'])) foreach ($this->group['group_members'] as $group):
                                    ?>
                                        <tr>
                                            <td><?php echo $group['id'];?></td>
                                            <td><?php echo $group['user'];?></td>
                                            <td><?php echo $group['user'];?></td>
                                            <td><?echo $this->group['group_info']['name']?></td>
                                            
                                    </td>
                                </tr>
                                <?php
                                endforeach;
                                ?>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- End Row -->
<?php
    Register::set('assets/tagsinput/jquery.tagsinput.min.js');
    Register::set('assets/toggles/toggles.min.js');
    Register::set('assets/timepicker/bootstrap-timepicker.min.js');
    Register::set('assets/jquery-multi-select/jquery.multi-select.js');
    Register::set('assets/jquery-multi-select/jquery.quicksearch.js');
    Register::set('assets/bootstrap-inputmask/bootstrap-inputmask.min.js');
    Register::set('assets/spinner/spinner.min.js');
    Register::set('assets/select2/select2.min.js');
    Register::set('js/group/group.js');
?>