<div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?echo $this->group['group_info']['name']?></h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <table id="datatable" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>邮箱</th>
                                            <th>姓名</th>
                                            <th>所属组</th>
                                            <th>操作</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                  <?php
                                    if(is_array($this->group['group_members'])) foreach ($this->group['group_members'] as $group):
                                    ?>
                                        <tr>
                                            <td><?php echo $group['id'];?></td>
                                            <td><?php echo $group['user'];?></td>
                                            <td><?php echo $group['user'];?></td>
                                            <td><?echo $this->group['group_info']['name']?></td>
                                            <td>   <a href="/group/show?id=<?php echo $group['group_info']['id'];?>"><button class="btn btn-icon btn-primary m-b-5"> <i class="fa fa-star"></i> </button></a> 
                                    </td>
                                </tr>
                                <?php
                                endforeach;
                                ?>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div> <!-- End Row -->
<?php
    Register::set('js/group/group.js');
?>