<?php 
  if(!isMobile()){

?>
<div class="row">
  <div class="col-sm-12">
    <div class="bg-picture" style="background-image:url('/public/img/bg-niagara.png');margin-bottom: 20px; margin: 0px 0px 20px 0px;">
     
    </div>
  </div>
</div>
<?php }?>
<div class="row">
  <div class="col-md-3 col-sm-6">
    <div class="widget-panel widget-style-1 bg-pink">
      <a href="/flow/list"><i class="fa fa-edit"></i></a>
      <h2 class="m-0 counter text-white">0</h2>
      <div class="text-white">新建申请</div></div>
  </div>
  <div class="col-md-3 col-sm-6">
    <div class="widget-panel widget-style-1 bg-warning">
      <a href="/apply/list"><i class="fa fa-file-text-o"></i></a>
      <h2 class="m-0 counter text-white"><?php echo $this->counter['counter_apply']?></h2>
      <div class="text-white">我的申请</div></div>
  </div>
  <div class="col-md-3 col-sm-6">
    <div class="widget-panel widget-style-1 bg-info">
      <a href="/approval/list"><i class="fa fa-clipboard"></i></a>
      <h2 class="m-0 counter text-white"><?=$this->counter['counter_audit']?></h2>
      <div class="text-white">我的审批</div></div>
  </div>
  <div class="col-md-3 col-sm-6">
    <div class="widget-panel widget-style-1 bg-success">
      <i class="fa fa-list"></i>
      <h2 class="m-0 counter text-white"><?=$this->counter['counter_flows']?></h2>
      <div class="text-white">权限数量</div></div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">

      <div class="panel-body">
        <p>
          <span class="dropcap text-primary">N</span>iagara提供权限申请、审批和管理服务，为申请者提供“一步式”权限申请服务，为权限管理者提供权限流的创建和维护服务。
        </p>
        </div>
    </div>
  </div>
</div>
<?php
    Register::set('js/index/index.js');
?>