<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">流程创建</h3></div>
			<div class="panel-body">
				<form class="form-horizontal p-20" role="form" method="post" >
					<div class="form-group">
						<label class="col-md-2 control-label">流程摘要</label>
						<div class="col-md-10">
							<input type="text" class="form-control" value="" name="name"></div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">流程描述</label>
						<div class="col-md-10">
							<textarea class="form-control" rows="10" name="desc"></textarea>
						</div>
					</div>
					<div class="form-group plus">
						<label class="col-md-2 control-label">点击增加审批流程</label>
							<div class="col-md-10">
								<button type="button" class="btn spinner-up btn-primary"><i class="fa fa-plus"></i></button>
							</div>
           				</label>
					</div>
					
					<button type="submit" class="btn btn-purple">提交</button>
					<button type="" class="btn btn-warning">放弃</button>
				</form>
			</div><!-- panel-body -->
		</div><!-- panel -->
	</div><!-- col -->
</div>
<?php 
	echo '<script>var USERLIST='.json_encode($userlist).';</script>';
?>

<?php
    Register::set('assets/tagsinput/jquery.tagsinput.min.js');
    Register::set('assets/toggles/toggles.min.js');
    Register::set('assets/timepicker/bootstrap-timepicker.min.js');
    Register::set('assets/jquery-multi-select/jquery.multi-select.js');
    Register::set('assets/jquery-multi-select/jquery.quicksearch.js');
    Register::set('assets/bootstrap-inputmask/bootstrap-inputmask.min.js');
    Register::set('assets/spinner/spinner.min.js');
    Register::set('assets/select2/select2.min.js');
	Register::set('js/flow/flow.js');
?>