<div cass="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">流程列表</h3></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th>#</th>
										<th>名称</th>
										<th>创建时间</th>
										<th>状态</th>
										<th>已申请人数</th>
										<th>操作</th></tr>
								</thead>
								<tbody>
									<?php
										foreach ($this->flowlist as $flow):
											echo "<tr>";
											echo "<td>".$flow['flow_info']['flow_id']."</td>";
											echo "<td>".$flow['flow_info']['name']."</td>";
											echo "<td>".date("Y-m-d H:i:s",$flow['flow_info']['create_time'])."</td>";
											echo "<td>".$flow['flow_info']['status']."</td>";
											echo "<td>0</td>";
											echo "<td><a href=\"/apply/create?flow=".$flow['flow_info']['flow_id']."\"><button class=\"btn btn-icon btn-primary m-b-5\"> <i class=\"fa fa-star\"></i> </button></a> <button class=\"btn btn-icon btn-danger m-b-5\"> <i class=\"fa fa-remove\"></i> </button></td>";
											echo "</tr>";
										endforeach;
									?>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>		