<div cass="row">
<?php
	foreach ($this->flowlist as $flow):
?>
<div class="col-sm-6">
	<div class="panel">
		<div class="panel-body">
			<div class="media-main">

				<div class="info">
					<h4>
						<?=$flow['flow_info']['name']?>
					</h4>
					<p class="text-muted">
						<?=date("Y-m-d",$flow['flow_info']['create_time']).'创建';?>
					</p>
				</div>
					<div class="pull-right btn-group-sm">
					<a href="/apply/create?flow=<?=$flow['flow_info']['flow_id']?>" class="btn btn-success tooltips" data-placement="top" data-toggle="tooltip"
					data-original-title="立即申请">
						<i class="fa fa-pencil">
						</i> 申请
					</a>
					
				</div>
			</div>
			<div class="clearfix">
			</div>
		</div>
		<!-- panel-body -->
	</div>
	<!-- panel -->
</div>
<?php
	endforeach;
?>
</div>