<div cass="row">
<?php
	if($this->orderlist) foreach ($this->orderlist as $order):
?>
<div class="col-sm-6">
	<div class="panel">
		<div class="panel-body">
			<div class="media-main">
				<div class="pull-right btn-group-sm"><?=G::GetOrderStats($order['status'],true);?></div>
				<div class="info">
					<h4>
						<?=$order['summary']?>
					</h4>
					<p class="text-muted">
						<?=date("Y-m-d H:i",$order['create_time']).'创建';?>
						-
						<?=date("Y-m-d H:i",$order['update_time']).'更新';?>
					</p>
				</div>
				<hr>
				
					<div class="pull-right btn-group-sm">
					<a href="/apply/show?id=<?php echo $order['orderid'];?>" class="btn btn-success tooltips" data-placement="top" data-toggle="tooltip"
					data-original-title="查看">
						<i class="ion-eye">
						</i> 查看
					</a>
					
				</div>
			</div>
			<div class="clearfix">
			</div>
		</div>
		<!-- panel-body -->
	</div>
	<!-- panel -->
</div>
<?php
	endforeach;
?>
</div>