<div cass="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">待审批</h3></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th>#</th>
										<th>申请项目</th>
										<th>发起时间</th>
										<th>状态</th>
										<th>最后更新时间</th>
										<th>操作</th></tr>
								</thead>
								<tbody>
									<tr>
										<td>1</td>
										<td>电脑申请</td>
										<td>2016-12-07 15:40</td>
										<td>等待OPS操作</td>
										<td>2016-12-07 15:40</td>
										<td></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">已审批</h3></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th>#</th>
										<th>申请项目</th>
										<th>发起时间</th>
										<th>状态</th>
										<th>最后更新时间</th>
										<th>操作</th></tr>
								</thead>
								<tbody>
									<tr>
										<td>1</td>
										<td>电脑申请</td>
										<td>2016-12-07 15:40</td>
										<td>已通过</td>
										<td>2016-12-07 15:40</td>
										<td></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
